[workspace]
resolver = "2"
members = ["crates/mbar-core", "crates/mbar-ipc", "crates/mbar-aerospace", "crates/mbar-lua", "crates/mbar-macos", "crates/mbar", "crates/mbar-app"]

[workspace.package]
version = "0.6.0"
edition = "2021"
license = "GPL-3.0-only"
repository = "https://github.com/rubenvitt/mbar"
rust-version = "1.80"

[workspace.dependencies]
mbar-core = { path = "crates/mbar-core" }
mbar-ipc = { path = "crates/mbar-ipc" }
mbar-aerospace = { path = "crates/mbar-aerospace" }
mbar-macos = { path = "crates/mbar-macos" }
mbar-lua = { path = "crates/mbar-lua" }
mbar-app = { path = "crates/mbar-app" }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
log = "0.4"
libc = "0.2"
regex = "1"
fancy-regex = "0.19"

[profile.release]
lto = "fat"
codegen-units = 1
panic = "abort"
opt-level = 3
